# -*- coding: utf-8 -*-
"""flatten

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19VAVhJRA53aNuOcboLSl-LTvbicEAWyX
"""

list_to_flatten = [[1,'a',['cat'],2],[[[3]],'dog'],4,5]
flattened_list = []
def flatten(l):
  for item in l:
    if isinstance(item, list):
      flatten(item)
    else:
      flattened_list.append(item)
  return flattened_list

flatten(list_to_flatten)