# -*- coding: utf-8 -*-
"""reverse

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19VAVhJRA53aNuOcboLSl-LTvbicEAWyX
"""

list_to_reverse = [[1, 2], [3, 4], [5, 6, 7]]
list_to_reverse.reverse()
def reverse(l):  
  for sublist in range(len(list_to_reverse)):
    list_to_reverse[sublist] = list_to_reverse[sublist][::-1]
  return list_to_reverse

reverse(list_to_reverse)

